### ISSUE TITLE
hi,I have a question in radix_tree_it.hpp

### ISSUE THREAD

**Issue by youngjeff** [ytakano/radix_tree#10]
I can't understand  the function `copy(*this)` in the source code 
```
radix_tree_it<K, T> radix_tree_it<K, T>::operator++ (int)
{
    radix_tree_it<K, T> copy(*this);
    ++(*this);
    return copy;
}
```
I search the reference std::copy():
```
template <class InputIterator, class OutputIterator>
  OutputIterator copy (InputIterator first, InputIterator last, OutputIterator result);
```
copy() need 3 arguments, but there just has *this, how does it work?

**Comment by ytakano** [comment]
Hi,

The copy is a temporal variable.
So, you can interpret this as follows.

    radix_tree_it<K, T> radix_tree_it<K, T>::operator++ (int)
    {
        radix_tree_it<K, T> tmp(*this);
        ++(*this);
        return tmp;
    }

Sorry for confusing you.

**Comment by youngjeff** [comment]
thank you , i get it.
