### ISSUE TITLE
Gtest download fails due to changed download URL

### ISSUE THREAD

**Issue by VorpalBlade** [ytakano/radix_tree#11]
When building the tests, the build system tries to download gtest if it can not find it locally using the URL https://googletest.googlecode.com/files/gtest-1.7.0.zip, which is no longer valid after gtest moved to github.

**Comment by ytakano** [comment]
linked to https://github.com/google/googletest/archive/release-1.7.0.zip instead of googlecode's repository.
Thank you for your report.
