### ISSUE TITLE
radix_tree<uint32_t, uint32_t>

### ISSUE THREAD

**Issue by gpyalt** [ytakano/radix_tree#19]
Hi there, would it be possible to create a radix_tree storing uint32_t keys? I can't figure out a way to do it!

Thanks - greg

**Comment by ytakano** [comment]
Yes.
You have to implement operator[], ==, and <,
and functions, radix_substr, radix_join, and radix_length for your type.
See [exmaple2.cpp](https://github.com/ytakano/radix_tree/blob/master/examples/example2.cpp).
