### ISSUE TITLE
Does this library support structured data insertion and prefix-based lookups like IP addresses?

### ISSUE THREAD

**Issue by angelyouyou** [ytakano/radix_tree#21]
Does this library support structured data insertion and prefix-based lookups like IP addresses?

**Comment by ytakano** [comment]
Structured data insertion:
Yes. This can be used like std::map.
https://github.com/ytakano/radix_tree/blob/master/examples/example1.cpp

IP prefix matching:
Yes. See an example.
https://github.com/ytakano/radix_tree/blob/master/examples/example2.cpp

**Comment by angelyouyou** [comment]
@ytakano 

Can an example of IPv6 prefix matching be added to this exmaple2? Thanks very much.
