### ISSUE TITLE
Can an example of IPv6 prefix matching be added to exmaple2?

### ISSUE THREAD

**Issue by angelyouyou** [ytakano/radix_tree#22]
Can an example of IPv6 prefix matching be added to exmaple2? There are some different  s between IPv4 and IPv6 address.

**Comment by dsokoloski** [comment]
I've done it [here](https://gitlab.com/netify.ai/public/netify-agent/-/blob/master/include/nd-addr.h) using std::bitset.  Search for the class [ndRadixNetworkEntry](https://gitlab.com/netify.ai/public/netify-agent/-/blob/master/include/nd-addr.h#L372).

**Comment by angelyouyou** [comment]
OK.Thanks very much.
