### ISSUE TITLE
MIT okay?

### ISSUE THREAD

**Issue by Ironholds** [ytakano/radix_tree#8]
Heya,

I'm hoping to incorporate this into an R library (basically making header-only trie implementations available to users). You have any problem with an MIT-licensed end product with library metadata that identifies you as the author?

**Comment by ytakano** [comment]
Hi, Oliver

Yes, of course.
There is no problem to do that.

2016-07-03 10:08 GMT+09:00 Oliver Keyes <notifications@github.com>:
