### ISSUE TITLE
Serializing the radix tree

### ISSUE THREAD

**Issue by rapoth** [ytakano/radix_tree#9]
Hi,

Thanks for the wonderful library. Since I do not want to reconstruct the radix tree everytime I load my program, I was wondering if there is a way I can go about serializing the radix tree once I build it. Do you have any suggestions on how to achieve this efficiently?

Thanks!

**Comment by ytakano** [comment]
Hi,

Currently, the reconstruction is the only way for the serialization.
However, I think the reconstruction is not bad solution.
